ISAICP-6538: Rename EUA to OE Bootstrap Theme
openeuropa/oe_bootstrap_theme pull request #1
Opened 2021-06-08 09:53 UTC by claudiu-cristea

Jira issue(s):
- [ISAICP-6538](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/ISAICP-6538)

2021-06-10 16:37 UTC, pfrenssen submitted a review, later dismissed

2021-06-11 16:28 UTC, vever001 requested changes
I found some typos, for the rest it looks good.

2021-06-11 16:28 UTC, vever001 commented on oe_bootstrap_theme.libraries.yml
> +    assets/js/oe_boostrap_theme.script.js: {}
Typo, missing t: oe_boostrap_theme > oe_bootstrap_theme

2021-06-11 16:28 UTC, vever001 commented on oe_bootstrap_theme.libraries.yml
> +      assets/css/oe_boostrap_theme.style.css: {}
Typo, missing t: oe_boostrap_theme > oe_bootstrap_theme

2021-06-11 16:28 UTC, vever001 commented on src/Theme/OpenEuropaBoostrapThemePreRender.php
>  <?php
Same here for the filename, class and usages:
- OpenEuropaBoostrapThemePreRender.php > OpenEuropaBootstrapThemePreRender.php
- class OpenEuropaBoostrapThemePreRender > class OpenEuropaBootstrapThemePreRender
- and calls to that class

2021-06-12 15:24 UTC, claudiu-cristea commented
@vever001 it seems that I was hungry and I ate that "t" :) Fixed the remarks, thank you

2021-06-14 08:49 UTC, vever001 approved these changes
Looks good to me

2021-06-14 09:46 UTC, idimopoulos approved these changes

2021-06-14 11:07 UTC, brummbar approved these changes
Approving on behalf of @vever001 .

2021-06-14 11:09 UTC, merged