OEL-522: Drop Components module, use ECL Twig loader
openeuropa/oe_bootstrap_theme pull request #100
Opened 2021-10-29 06:54 UTC by claudiu-cristea

Original PR https://github.com/openeuropa/oe_bootstrap_theme/pull/91 (somehow, I've messed the OEL-522 branch and I had to recreate it)

2021-12-06 10:03 UTC, drishu requested changes

2021-12-06 10:03 UTC, drishu commented on modules/oe_bootstrap_theme_helper/tests/src/Kernel/BclComponentsOverrideTest.php
> + *
I suggest we add covers BclComponentLibraryLoader

2021-12-06 10:03 UTC, drishu commented on package.json
> +    "@openeuropa/bcl-builder": "^0.12.0",
we can upgrade to 14 now

2021-12-10 16:35 UTC, brummbar approved these changes

2021-12-10 16:59 UTC, drishu approved these changes

2021-12-10 16:59 UTC, merged