Oel 740
openeuropa/oe_bootstrap_theme pull request #108
Opened 2021-11-08 16:18 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-740

2021-11-09 14:14 UTC, drishu requested changes

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> + * @group batch1
remove this, we dont have batches set up

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/BasePatternAssert.php
> +declare(strict_types = 1);
this is a bit confusing for me, can we move these in their own folder outside the paragraphs

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/PatternAssertInterface.php
> +<?php
move in its own folder

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/TextFeaturedMediaAssert.php
> +<?php
move to own folder

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/AbstractKernelTestBase.php
> +  protected function setUp() {
```suggestion
  protected function setUp(): void {
```

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +  protected function setUp() {
```suggestion
  protected function setUp(): void {
```

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/ParagraphsTestBase.php
> +  protected function setUp() {
```suggestion
  protected function setUp(): void {
```

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/ParagraphsTestBase.php
> +  public static $modules = [
```suggestion
  protected static $modules = [
```

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +  public static $modules = [
there is no point to declare a $modules in ParagraphsTestBase and overwrite the complete list here, remove this and add in ParagraphsTestBase::modules the complete list of what you need (and only the ones you need)

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/MediaParagraphsTest.php
> +    $this->container->get('entity_type.manager')->getAccessControlHandler('media')->resetCache();
no point in flushing before, we have the one after

2021-11-09 14:14 UTC, drishu commented on tests/src/Kernel/Paragraphs/TextFeaturedMediaAssert.php
> +class TextFeaturedMediaAssert extends BasePatternAssert {
where is this class used ?

2021-11-10 09:33 UTC, drishu approved these changes

2021-11-10 09:37 UTC, GilNovacomm approved these changes

2021-11-10 09:41 UTC, merged