OEL-750: Upgrade BCL to 0.13.0 (all)
openeuropa/oe_bootstrap_theme pull request #113
Opened 2021-11-17 14:54 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-750

2021-11-24 15:02 UTC, brummbar requested changes, later dismissed
I have many changes to introduce but I cannot add them all here. Let's try to move forward with this and we rework patterns in a separate ticket.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/banner/banner.ui_patterns.yml
> +      preview: "my-2"
We shouldn't expose presentation details like classes in the pattern, we need to offer a layer to pass data only.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/date_block/date_block.ui_patterns.yml
> +  label: "Date Block"
Don't capitalise words.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/link/link.ui_patterns.yml
> +      label: Disabled
Wrong label.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/link/link.ui_patterns.yml
> +      description: Add extra "text-underline-hover" class to link item.
Explain what it does, not the technical detail (class name).

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/link/link.ui_patterns.yml
> +      description: When enabled, not add the margin class to the icon
```suggestion
      description: When set to true, prevents margins to be added to the icon.
```

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/link/link.ui_patterns.yml
> +      description: Add id attribute to the link.
```suggestion
      description: A specific ID to use for the link.
```
Not sure this should be left at all.

2021-11-24 15:02 UTC, brummbar commented on tests/src/Kernel/fixtures/markup_rendering_patterns/banner.yml
> +      'bcl-banner__content': "EU Budget for the future"
This is not a valid selector, but tests are green, which makes me wonder.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/link/link.ui_patterns.yml
>        label: Button id
This is not a button though.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/banner/pattern-banner.html.twig
> +  image: image,
By looking at the components page, I see that the image is shown in all the variants. We shouldn't pass the image if we are rendering a variant where is not needed. It seems it's not handled on the BCL side.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
> +        '#markup': "https://placeimg.com/1000/500/tech"
Why this line?

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/listing/listing.ui_patterns.yml
> +              '#markup' : '<a class="text-underline-hover" href="/example">Card title 1</a>'
Why this change? I don't think the class is needed.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
> +      label: "Date that will be shown with Date Block."
```suggestion
      label: 'Date that will be rendered with the "Date block" pattern.'
```

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/date_block/date_block.ui_patterns.yml
> +      preview: "2021-05-27"
I don't like this much. We are forced to specify the data twice to be passed in the pattern. Instead, we can simply accept one single parameter, like a DrupalDateTime or a formatted date, and then in a preprocess elaborate the various pieces of the date.

2021-11-24 15:02 UTC, brummbar commented on tests/src/Kernel/fixtures/markup_rendering_patterns/banner.yml
> +      'bcl-banner__content': "EU Budget for the future"
I check and there are around 50 failures due to the selector being ignored, which is not good. I'll create another ticket for this.

2021-11-24 15:02 UTC, brummbar commented on templates/patterns/banner/pattern-banner.html.twig
> +} %}
We need to pass only the expected parameters.
```suggestion
} only %}
```

2021-11-24 15:02 UTC, brummbar commented on tests/src/Kernel/fixtures/markup_rendering_patterns/banner.yml
> +      'p': "Innovation, economy, environment and geopolitics"
Let's already put here some proper selectors though.

2021-11-24 15:02 UTC, brummbar commented on tests/src/Kernel/fixtures/markup_rendering_patterns/banner.yml
> +      'a': "Subscribe"
This is way too generic, we need to assert that we are rendering using the correct bcl template. At least something like `.bcl-banner__content a[href="https://example.com"]: Subscribe`.

2021-11-24 15:37 UTC, escuriola commented on tests/src/Kernel/fixtures/markup_rendering_patterns/banner.yml
> +      'bcl-banner__content': "EU Budget for the future"
@brummbar contains assertion selectors are not used, only checks the texts exists on the html:
```
// Assert presence of given strings.
    foreach ($assertions['contains'] as $string) {

      $this->assertStringContainsString($string, $html);

    }
```

Sometimes we use not selector and use for instance anchor_1, anchor_2, and so on...

2021-11-25 09:41 UTC, escuriola commented on templates/patterns/card/card.ui_patterns.yml
> +        '#markup': "https://placeimg.com/1000/500/tech"
Because of the search variant of the card. Has a special way to get the image.

2021-11-25 10:13 UTC, escuriola commented on templates/patterns/banner/banner.ui_patterns.yml
> +      preview: "my-2"
@brummbar @drishu We would need an example of how to manage this change. Convert "description" to "array" or to "render"? Is there any example where we can review this?

2021-11-25 10:18 UTC, escuriola commented on tests/src/Kernel/fixtures/markup_rendering_patterns/banner.yml
> +      'bcl-banner__content': "EU Budget for the future"
Are you agree to manage all this in another ticket @brummbar @drishu ? Do you want to create the Jira ticket to the next sprint?

2021-11-26 16:38 UTC, drishu approved these changes
Some improvements will be needed but we agreed to follow up

2021-11-26 16:41 UTC, timpevi approved these changes

2021-11-26 16:41 UTC, Maxfire approved these changes

2021-11-26 16:42 UTC, merged