OEL-494: Create 'File' paragraph component
openeuropa/oe_bootstrap_theme pull request #127
Opened 2021-11-29 18:10 UTC by Maxfire

Jira issue(s):
- [OEL-494](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-494)

2021-12-02 14:32 UTC, GilNovacomm approved these changes, later dismissed
All is well.

2021-12-08 17:01 UTC, brummbar requested changes

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/pattern-file.html.twig
> +  {% set bcl_icon_path = '/assets/icons/bootstrap-icons.svg' %}
Let's do like this https://github.com/openeuropa/oe_theme/blob/3.x/oe_theme.theme#L74 .
We are introducing this path over and over, but we can just put a generic preprocess and defined the value there.
Search for the path and remove it from everywhere in this PR itself.

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/pattern-file.html.twig
> +    translation: translation,
Why we are mixing quoted and unquoted?

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/file.ui_patterns.yml
> +      type: object
Why we don't use array here?

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/file.ui_patterns.yml
> +        id: ""
This shouldn't be needed.

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/file.ui_patterns.yml
> +          icon_position: "after"
Let's simplify this by removing icon position. We pass a string only to label.

2021-12-08 17:01 UTC, brummbar commented on tests/src/Kernel/Paragraphs/FileParagraphTest.php
> +  public function testFilePatternRendering(array $file) {
We shouldn't test the pattern here, for that we have the markup rendering tests. We need to test only the paragraph.

2021-12-08 17:01 UTC, brummbar commented on tests/src/Kernel/Paragraphs/FileParagraphTest.php
> +class FileParagraphTest extends ParagraphsTestBase {
We are overriding the form above, so we need to test the paragraph creation too.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    ];
This is not correct, it should be all handled in the template and not at paragraph level.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/config/overrides/core.entity_form_display.media.document.default.yml
> +langcode: en
Why is this overridden, I didn't find significant differences with the one provided by oe_media.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/config/overrides/core.entity_form_display.paragraph.oe_document.default.yml
> +langcode: en
Same in here, the only extra is the translation field, which shouldn't be exported (make sure to not have multilingual modules enabled when exporting the configuration).

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/config/overrides/core.entity_view_display.media.document.default.yml
> +langcode: en
Same with this file, looks the same as oe_paragraphs to me.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/config/overrides/core.entity_view_display.paragraph.oe_document.default.yml
> +langcode: en
Same.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    $variables['translation']['id'] = 'language-dropdown' . rand(0, 99);
If we have to generate an ID, always use `\Drupal\Component\Utility\Html::getUniqueId()`.

2021-12-08 17:01 UTC, brummbar commented on src/DocumentMediaValueExtractor.php
> + * Extracts a FileValueObject from a document media.
Put a comment that this is extracted from oe_theme.

2021-12-08 17:01 UTC, brummbar commented on src/DocumentMediaValueExtractor.php
> + * Extracts a FileValueObject from a document media.
Let's also add `@internal` for now.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_helper/oe_bootstrap_theme_helper.services.yml
> +  oe_bootstrap_theme_helper.twig_extension.twig_extension:
```suggestion
  oe_bootstrap_theme_helper.twig_extension:
```

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_helper/src/TwigExtension/TwigExtension.php
> +    foreach ($extension_mapping as $file_type => $extensions) {
```suggestion
    foreach ($extension_mapping as $icon => $extensions) {
```

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +  $type = $media->get('oe_media_file_type')->value;
Most of this code is done inside `DocumentMediaValueExtractor::getFileValue()`, the way this is implemented now I get a critical error due to missing extension when I upload a remote file.
Let's follow a bit more how oe_theme is done, as I think it's beneficial:

1. Let's style the media entity itself, instead of the paragraph. Move to media entity preprocess.
2. The paragraph formatter will simply render the entity with the default view mode (look in `oe_theme_preprocess_media__document__default()`).

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    $variables['file']->setLanguageCode($file_entity->language()->getName());
The language code isn't a name, it's the code itself.

2021-12-08 17:01 UTC, brummbar commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +      ];
All the meta preprocessing should go in preprocess functions if we use a single meta field. Check oe_theme, we have checks for missing file size too.

2021-12-08 17:01 UTC, brummbar commented on src/ValueObject/FileValueObject.php
> +    return $extension ?? pathinfo($this->name, PATHINFO_EXTENSION);
Let's improve on oe_theme by doing this:
```
    if ($this->extension === NULL) {
      $mime_types = new MimeTypes();
      $extension = $mime_types->getExtension($this->getMime());
      $this->extension = $extension ?? pathinfo($this->name, PATHINFO_EXTENSION);
    }

    return $this->extension;
```

Note: I have this code because I was debugging one error reported above and I kept getting inside this function over and over and over... 😄

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/file.ui_patterns.yml
> +    translation:
This can be multiple translations, so let's use translation**s**.

2021-12-08 17:01 UTC, brummbar commented on templates/patterns/file/file.ui_patterns.yml
> +              path: "/example.html"
Let's simplify for the download label, we don't need to specify it in ALL the translations. Let's put a button_label on the top level, like it's done in oe_theme. So we avoid to repeat it here.
Fine to keep meta as single entry, but then we need to pass the processed meta information from the preprocess.
Download becomes url with a sigle path to the file, language we put the language_code and translate when passing down to the bcl template.

2021-12-09 09:59 UTC, escuriola commented on templates/patterns/file/pattern-file.html.twig
> +  {% set bcl_icon_path = '/assets/icons/bootstrap-icons.svg' %}
We already have this in oe_bootstrap_theme.theme (https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/oe_bootstrap_theme.theme#L20)

2021-12-09 10:17 UTC, escuriola commented on templates/patterns/file/file.ui_patterns.yml
> +      type: object
Not compatible with bcl-file component

2021-12-10 11:02 UTC, escuriola commented on modules/oe_bootstrap_theme_paragraphs/config/overrides/core.entity_form_display.media.document.default.yml
> +langcode: en
None of these files were replaced because they were not listed in oe_bootstrap_theme_paragraphs.install

2021-12-14 16:34 UTC, brummbar commented on templates/patterns/file/pattern-file.html.twig
> +  {% set bcl_icon_path = '/assets/icons/bootstrap-icons.svg' %}
Then why we keep defining the variable over and over and over?

2021-12-21 11:00 UTC, escuriola requested changes

2021-12-21 11:00 UTC, escuriola commented on composer.json
> +        "openeuropa/oe_paragraphs": "dev-master",
After the meeting with Francesco about testing in oe_showcase I think oe_paragraph, oe_media, etc., must be moved to require section but please confirm with Francesco.

2021-12-21 13:37 UTC, escuriola submitted a review, later dismissed

2022-12-16 14:23 UTC, closed without merging