OEL-755 (+OEL 490) - Listing with date and mangage variants.
openeuropa/oe_bootstrap_theme pull request #128
Opened 2021-11-30 10:08 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-755
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-490

2021-12-02 12:14 UTC, abel-santos-corral reviewed
@escuriola there must be a test for List item block --> add a link which is internal. Check that creation date and bundle are shown in the card. Check in file ListItemParagraphsTest and search "Variant - default with internal link." t get the example.

2021-12-02 12:14 UTC, abel-santos-corral commented on tests/src/Kernel/Paragraphs/ListItemParagraphsTest.php
> +      'http://www.example.com/',
Add the number at the end of the url, when declaring the paragraph you have added an integer of the item value.

2021-12-02 12:14 UTC, abel-santos-corral commented on tests/src/Kernel/Paragraphs/ListItemParagraphsTest.php
> +    $link_element = $crawler->filter('h5.card-title a');
Add test for title also to check that is 'Example ' . $i

2021-12-02 12:14 UTC, abel-santos-corral commented on tests/src/Kernel/Paragraphs/ListItemParagraphsTest.php
> +  }
Add 2 tests, both have informed the image and the date. Then simulate those cases that user may have passed from one type to other:
- 'date'
- 'default'
We must ensure that the right stuff is showed even though the user may have done 'date -> default' or 'default -> date'

2021-12-02 12:14 UTC, abel-santos-corral commented on tests/src/Kernel/PatternAssertions/ListingAssertion.php
> + * Class for asserting links block paragraphs.
Is asserting listing, not links. Rename it, please.

2021-12-02 12:14 UTC, abel-santos-corral commented on tests/src/Kernel/PatternAssertions/ListingAssertion.php
> +  protected function assertImage(Crawler $crawler, File $file): void {
This seems to be used only at one place. Maybe is not necessary to split the code to a function.

2021-12-02 12:14 UTC, abel-santos-corral commented on templates/patterns/list_item/pattern-list-item.html.twig
> +  - "meta" (array) (default: []): Meta information for the Content Item.
@escuriola , it seems that the 'Content Item' maybe has to be List item. And we should change all the rest of the Parameters.

2021-12-02 12:14 UTC, abel-santos-corral commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    if ($variables['variant'] === 'thumbnail_secondary') {
Check, there's code in the twig for this. We should leave only at one place.

2021-12-02 14:44 UTC, escuriola commented on tests/src/Kernel/PatternAssertions/ListingAssertion.php
> +  protected function assertImage(Crawler $crawler, File $file): void {
Is used twice

2022-01-19 16:45 UTC, drishu requested changes
The review is incomplete, it is already a lot and I need to see this in place before I can finish.
Also I didn't review the listing item, I'm waiting on feedback but would like to remove it entirely.

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
>  function oe_bootstrap_theme_preprocess_paragraph__oe_list_item_block(array &$variables): void {
```suggestion
function oe_bootstrap_theme_paragraphs_preprocess_paragraph__oe_list_item_block(array &$variables): void {
```
I realised we made a mistake, the "hook_" naming convention was not respected

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +  $variables['columns'] = oe_bootstrap_theme_get_bcl_layout_mapping($variables['variant'], $paragraph->get('field_oe_list_item_block_layout')->first()->value);
```suggestion
  $variables['columns'] = oe_bootstrap_theme_paragraphs_get_mapped_layout($paragraph->get('field_oe_list_item_block_layout')->first()->value, $variables['variant']);
```
again the module prefix and I moved variant last since I want a default value there

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
>          'position' => 'top',
we will move this to the pattern preprocess, we should send only variant and fields, no visual formatting related

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +        'rounded' => 1,
we will move this to the pattern preprocess, we should send only variant and fields, no visual formatting related

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    $date = get_date_for_list_item_paragraph($item->entity, $variables);
```suggestion
    $date = oe_bootstrap_theme_paragraphs_get_listing_date($item->entity, $variables);
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
>        }
```
$metas[] = $item_meta->value;
```
lets send just content and we format in the pattern

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    $title = [
we should check also for empty url, like <nolink>
```suggestion
    $url = $item->entity->get('field_oe_link')->first()->getUrl()->toString();
    if (empty($url)) {
      $title = $item->entity->field_oe_title->value;
    }
    else ..
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
>        'title' => [
```suggestion
      'title' => $title,
```
again we should not format for visual here

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
>        'text' => [
```suggestion
      'text' => $item->entity->field_oe_text_long->value,
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
for the $variable['link'], pls remove 'icon', it just needs path and we should set that in the pattern process, its not paragraphs related

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +function oe_bootstrap_theme_get_bcl_layout_mapping(string $variant, string $layout): string {
```suggestion
function oe__bootstrap_theme_paragraphs_get_mapped_layout(string $layout, string $variant = 'default'): string {
```
{module_name}_tralala and as mentioned I think a default value for variant is a good idea

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +      return $variant === 'highlight' ? "highlight-2-col" : "default-2-col";
we can make this simpler like so 
```suggestion
       return "$variant-2-col";
```
same for the others

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> + * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
I know the editor adds these but I think we should not use them, for the reason that if the implementation of this function changes that these are not valid anymore (in a compiled language it makes sense but php not as much)

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +  $contentItem = [];
remove

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +  if (!UrlHelper::isExternal($paragraph->get('field_oe_link')->first()->getUrl()->toString())) {
the Url class already has isExternal(), also we should always try to exit early to code clarity
```suggestion
  if ($paragraph->get('field_oe_link')->first()->getUrl()->isExternal()) {
    return [];
  }
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    foreach ($urlOptions as $key => $value) {
instead of this loop and the immediate if, we could have just one check and early exit
```
if (empty($urlOptions) || !isset($urlOptions['node'])) {
    return [];
  }
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +  return $contentItem;
```suggestion
  return [
    'date' => $formatted_date,
    'bundle_name' => $bundle_label,
  ];
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +        $formatted_date = \Drupal::service('date.formatter')->format($date, 'custom', 'j F Y');
this date format 'j F Y' I see is common for us in OEL, we should add a date format and use that one instead of 'custom' as it is more flexible and overridable.

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +          '#type' => 'inline_template',
we should move this formatting into the pattern preprocess

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +function get_date_for_list_item_paragraph(Paragraph $paragraph, array $variables): array {
```suggestion
function oe_bootstrap_theme_paragraphs_get_listing_date(Paragraph $paragraph, array $variables): array {
```

2022-01-19 16:45 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> + * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
remove these

2022-01-19 16:45 UTC, drishu commented on oe_bootstrap_theme.theme
> +  }
so we move all the formatting that concerns the pattern here
```
if (isset($variables['link'])) {
    $variables['link']['icon'] = [
      'path' => $variables['bcl_icon_path'],
    ];
  }

  if (isset($variables['items'])) {
    // @todo: align this with card after refactoring.
    foreach ($variables['items'] as $key => $value) {
      $item = &$variables['items'][$key];

      $item['title'] = [
        'content' => $item['title'],
      ];
      $item['text'] = [
        'content' => $item['text'],
        'classes' => $variables['variant'] === 'highlight' ? 'mb-2' : 'mb-3',
      ];

      if (!empty($item['image'])) {
        $item['image']['rounded'] = 1;
      }

      $metas = [];
      foreach ($item['badges'] as $item_meta) {
        $metas[] = [
          'label' => $item_meta,
          'background' => 'primary',
        ];
      }
      $item['badges'] = $metas;

      if (!empty($item['content'])) {
        $item['content'] = [
          '#type' => 'inline_template',
          '#template' => '<div><span class="text-muted d-md-inline d-block me-4 mb-2 mb-md-0">{{ bundle_name }}</span><span class="d-md-inline d-block text-muted mb-2 mb-md-0">{{ date }}</span></div>',
          '#context' => [
            'date' => $item['content']['date'],
            'bundle_name' => $item['content']['bundle_name'],
          ],
        ];
      }
    }
  }
```

something like this but please test, this is just a scratch

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
> +        default-1-col: 'default-1-col (default)'
I've given this dome thought, I think we should add variants: "default", "highlight", "date" and for 'columns': "one_column", "two_columns", "three_columns".
This way we probably wont need "oe_bootstrap_theme_get_bcl_layout_mapping()" its code would move in the pattern template or preprocess

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
>      title_tag:
I think we should remove this in the spirit of refactoring these patterns

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
>      alignment:
I think we should remove also this one and go with the default, what do you think ?

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
> +            content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut ex tristique, dignissim sem ac, bibendum est. Sed vehicula lorem non nunc tincidunt hendrerit. Nunc tristiq
since this formatting will be handled in the pattern preprocess we will have to refactor this
```
- title:
            '#markup' : '<a href="/example">Card title 1</a>'
          text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut ex tristique, dignissim sem ac, bibendum est. Sed vehicula lorem non nunc tincidunt hendrerit. Nunc tristique ante et fringilla fermentum.'
          image:
            path: 'https://placeimg.com/600/400/people'
            alt: 'alt img'
          content:
            date: '17 October 2019'
            bundle_name: 'Article'
```
something like this

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
>          icon:
remove icon, this will be in the preprocess

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
> +            position: 'top'
remove this as we do it in the prerocess, doube check all these preview values after refactor

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/pattern-listing.html.twig
>    'title_tag': title_tag,
remove

2022-01-19 16:45 UTC, drishu commented on templates/patterns/listing/pattern-listing.html.twig
>    'alignment': alignment,
remove ? not sure about this one

2022-01-19 16:45 UTC, drishu commented on tests/src/Functional/ParagraphsTest.php
> +    $this->submitForm([], 'Add another item');
if we use only index "0" is there a point in adding another item ?

2022-01-19 16:45 UTC, drishu commented on tests/src/Kernel/PatternAssertions/LinksBlockAssertion.php
> +class LinksBlockAssertion extends ParagraphsTestBase {
I missed this the first time, this should extend the BasePatternAssert, same for ListingAssertion

2022-01-19 16:45 UTC, drishu commented on tests/src/Kernel/PatternAssertions/ListingAssertion.php
> +class ListingAssertion extends ParagraphsTestBase {
```suggestion
class ListingAssertion extends BasePatternAssert {
```

2022-01-19 16:45 UTC, drishu commented on tests/src/Kernel/PatternAssertions/ListingAssertion.php
> + * Class for asserting Listing paragraphs.
These classes are for easy, reusable and maintainable testing or pattern rendering, so not related to paragraphs, pls reformulate

2022-01-19 16:45 UTC, drishu commented on tests/src/Kernel/fixtures/markup_rendering_patterns/listing.yml
> +            path: 'https://placeimg.com/600/400/people'
update the values after refactor

2022-02-25 11:24 UTC, escuriola commented
Obsolete. There is a new one PR.

2022-02-25 11:24 UTC, closed without merging