OEL-492: Paragraphs - Rich text - Theming
openeuropa/oe_bootstrap_theme pull request #138
Opened 2021-12-07 11:13 UTC by abel-santos-corral

Jira issue(s):
- [OEL-492](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-492)

2021-12-09 08:44 UTC, escuriola requested changes

2021-12-09 08:44 UTC, escuriola commented on kits/default/package.json
> +    "@openeuropa/bcl-builder": "0.15.0",
Do not upgrade to this version, is still on development and blocks this if we have to wait until v15 is out.

2021-12-09 08:44 UTC, escuriola commented on package.json
> +    "@openeuropa/bcl-builder": "0.15.0",
Same as above

2021-12-09 08:44 UTC, escuriola commented on tests/src/Kernel/Paragraphs/RichTextTest.php
> +    $text_original = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare et elit a dictum. Maecenas lacinia eros quis eros iaculis, sit amet bibendum massa facilisis. Intege
It's not possible to test more "html" is this text? I understand that rich text is text with some kind of format, as bold, italics, headings, underlined... and this is plain text.

2021-12-10 08:06 UTC, escuriola approved these changes, later dismissed

2021-12-10 10:15 UTC, drishu requested changes

2021-12-10 10:15 UTC, drishu commented on templates/overrides/field/field--paragraph--field-oe-title--oe-rich-text.html.twig
> +{#
I see it was done the same in oe_theme but I'd rather have all this paragraphs theming in one place, and crate paragraph--oe-rich-text.html.twig with
```
<h4 class="fw-bold mb-4">{{ content.field_oe_title }}</h2>
{{ content|without('field_oe_title') }}
```
I added the same class as the one in listing item block, I see in netlify in paragraphs its the same used, so lets go with this for now

2021-12-10 10:15 UTC, drishu commented on tests/src/Kernel/Paragraphs/ParagraphsTestBase.php
> +    'ckeditor',
you don't need these changes

2021-12-11 10:30 UTC, drishu requested changes

2021-12-11 10:30 UTC, drishu commented on tests/src/Kernel/Paragraphs/RichTextTest.php
> +    // Create a text format and associate CKEditor.
CKEditor is nowhere in this test, but even so, it is obvious what that code does so the comment is redundant

2021-12-11 10:30 UTC, drishu commented on tests/src/Kernel/Paragraphs/RichTextTest.php
> +    // Create Rich text paragraph.
remove this comment

2021-12-11 10:30 UTC, drishu commented on tests/src/Kernel/Paragraphs/RichTextTest.php
> +    // Testing: Rich text.
this comment is not needed

2021-12-11 10:30 UTC, drishu commented on tests/src/Kernel/Paragraphs/ParagraphsTestBase.php
> +    'editor',
this module is not needed

2021-12-13 10:03 UTC, drishu approved these changes

2021-12-13 10:20 UTC, escuriola approved these changes

2021-12-13 10:23 UTC, merged