OEL-961: Fix dropbutton links.
openeuropa/oe_bootstrap_theme pull request #147
Opened 2022-01-03 14:20 UTC by escuriola

Jira issue(s):
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-961

2022-01-05 15:06 UTC, drishu requested changes

2022-01-05 15:06 UTC, drishu commented on includes/menu.inc
> +function dropbutton_add_required_classes(array &$links): void {
```suggestion
function oe_bootstrap_theme_add_dropbutton_classes(array &$links): void {
```

2022-01-05 15:06 UTC, drishu commented on includes/menu.inc
> + * Add required classes to dropbutton links.
```suggestion
 * Adds required classes to dropbutton links.
```

2022-01-05 15:06 UTC, drishu commented on includes/menu.inc
> +  dropbutton_add_required_classes($links);
```suggestion
  oe_bootstrap_theme_add_dropbutton_classes($links);
```

2022-01-06 10:16 UTC, drishu submitted a review, later dismissed

2022-01-06 11:58 UTC, abel-santos-corral commented on tests/src/Kernel/DropbuttonTest.php
> +    $active = $crawler->filter('li:nth-child(1) a')->text();
```suggestion
    $this->assertEquals('Link 1', trim($items->eq(0)->text()));
    $this->assertEquals('Link 2', trim($items->eq(1)->text()));
    $this->assertEquals('Link 3', trim($items->eq(2)->text()));
    $this->assertEquals('Link 4', trim($items->eq(3)->text()));
    $this->assertEquals('Link 5', trim($items->eq(4)->text()));
```

2022-01-06 11:58 UTC, abel-santos-corral commented on tests/src/Kernel/DropbuttonTest.php
> +    $active = $crawler->filter('li:nth-child(1) a')->text();
That can be done with fewer lines as the suggestion (already tested in local).

2022-01-06 12:11 UTC, abel-santos-corral approved these changes

2022-01-07 09:15 UTC, drishu approved these changes

2022-01-07 09:15 UTC, merged