OEL-779: Review patterns: Button, Carousel and remove several patterns.
openeuropa/oe_bootstrap_theme pull request #152
Opened 2022-01-12 08:30 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-779

2022-01-12 16:39 UTC, escuriola commented on templates/patterns/button/pattern-button.html.twig
> +} only %}
in disabled add default disabled: disabled|default(attributes.disabled)

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/button/button.ui_patterns.yml
> +      preview: 'primary'
Not necessary, delete it please and if present, delete setting default value at markup rendering test.

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/button/button.ui_patterns.yml
>        preview: false
Not necessary, delete it please and if present, delete setting default value at markup rendering test.

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/button/button.ui_patterns.yml
> +        size: 's'
This can be deleted, the default value is 's'. Check if also set at markup rendering test, then there can be eliminated.

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
>        preview: true
This can be deleted, the default value is 'true'. Check if also set at markup rendering test, then there can be eliminated.

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +      preview: true
This can be deleted, the default value is 'true'. Check if also set at markup rendering test, then there can be eliminated.

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +      preview: false
This can be deleted, the default value is 'false'. Check if also set at markup rendering test, then there can be eliminated.

2022-01-17 11:50 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +              uri: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1140&h=385&q=80'
@escuriola, we should check together, there are 3 different web providers for images. Maybe we can check and use only one. This is not a key change.

2022-01-17 11:50 UTC, abel-santos-corral commented on tests/src/Kernel/fixtures/markup_rendering_patterns/button.yml
> +        size: 's'
Not necessary

2022-01-17 11:50 UTC, abel-santos-corral commented on tests/src/Kernel/fixtures/markup_rendering_patterns/button.yml
> +        size: 's'
Not necessary

2022-01-17 11:50 UTC, abel-santos-corral commented on tests/src/Kernel/fixtures/markup_rendering_patterns/carousel.yml
>          autoplay: true
Not necessary. If set below, can be deleted too.

2022-01-17 11:50 UTC, abel-santos-corral commented on tests/src/Kernel/fixtures/markup_rendering_patterns/carousel.yml
>          with_controls: true
Not necessary. If set below, can be deleted too.

2022-01-17 14:48 UTC, abel-santos-corral approved these changes, later dismissed

2022-01-20 14:04 UTC, brummbar requested changes

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/button/pattern-button.html.twig
>    'spinner': spinner,
Didn't we remove the spinner?

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/button/button.ui_patterns.yml
> +    style:
We should put these back as variants to be in line with the badge and oe_theme.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/button/button.ui_patterns.yml
> +      label: 'Icon'
Let's pass just the name as usual. We can then expand it in the template using a filter like oe_theme does (which just expands from name to array with path).

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/button/button.ui_patterns.yml
> -    assistive_text:
This we said we remove, right? We talked about it but I don't remember.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/button/pattern-button.html.twig
>    'id': button_id,
We don't have button_id, nor clean_class variables, where are they coming from? Maybe a leftover.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/carousel/carousel.ui_patterns.yml
>      with_indicators:
`show_indicators`.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/carousel/carousel.ui_patterns.yml
>      with_controls:
`show_controls`.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +    dark:
maybe make this a "theme" option with select and two options, so we can add more in the future?

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +                class: 'd-block w-100'
These classes are mandatory or the carousel won't look nice. We need to pass them in the pattern template without having the user to pass them explicitly.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/modal/pattern-modal.html.twig
> +    style: btn_style,
Let's be verbose, "button_variant".

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/modal/pattern-modal.html.twig
> +    style: btn_style,
Also note that we are generating the id in the template, which is wrong.

2022-01-20 14:04 UTC, brummbar commented on templates/patterns/modal/pattern-modal.html.twig
> +    style: btn_style,
Actually let's move everything to a "button:" entry so we can pass all the button pattern info in there.

2022-01-21 16:03 UTC, brummbar commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +    dark:
We went for "dark_mode" like phones.

2022-01-24 08:26 UTC, abel-santos-corral reviewed
Review the 3 changes proposed, please.

2022-01-24 08:26 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +      description: 'Default to true. If set to false the carousel will not slide automatically.'
As said, must be 'Defaults to true....'

2022-01-24 08:26 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +      description: 'Default to true. If set to false, the carousel will need to be instantiated via javascript.'
Write it as 'Defaults to true....'

2022-01-24 08:26 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +      description: 'Enable the dark mode. Default to false.'
As said, please, use 'Defaults to false.'

2022-01-24 08:36 UTC, abel-santos-corral approved these changes

2022-01-24 08:36 UTC, abel-santos-corral commented on templates/patterns/carousel/carousel.ui_patterns.yml
> +      description: 'Default to true. If set to false the carousel will not slide automatically.'
Set as defaults to true. With s.

2022-01-24 08:49 UTC, brummbar approved these changes

2022-01-24 08:49 UTC, merged