OEL-779: Review Patterns: Nav, Offcanvas, Pagination, Progress, Table, Timeline
openeuropa/oe_bootstrap_theme pull request #154
Opened 2022-01-13 10:39 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-779

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/nav/nav.ui_patterns.yml
>        preview: false
Not necessary, default value is false.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/nav/nav.ui_patterns.yml
> +      description: 'If true, shows the tabs content container.'
Please, to homogenize, the formula 'When enable' could be used.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/nav/nav.ui_patterns.yml
> +      description: 'If true, use nav style for show items instead unordered lists.'
It seemed better as 'When enabled'.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/nav/nav.ui_patterns.yml
> +      description: 'If true, use nav style for show items instead unordered lists.'
```suggestion
      description: 'When enabled, use navigation style for show items instead unordered lists.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/offcanvas/offcanvas.ui_patterns.yml
> +      description: 'If true, enable body scrolling when offcanvas is displayed. False by default.'
```suggestion
      description: 'When enabled, allows body scrolling when offcanvas is displayed. False by default.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/offcanvas/offcanvas.ui_patterns.yml
>        preview: false
Not necessary, is false by default. To be checked at markup rendering test.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/offcanvas/offcanvas.ui_patterns.yml
> +      label: 'Icon position'
Add description, please. Something as  'Sets the position of the icon regarding the text'. We must check, the icon position is in another item in another PR )this field is present at button, banner, link and off-canvas. We must ensure homogeneity between all patterns.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/pagination/pagination.ui_patterns.yml
> +      description: 'Use icon instead of link labels to previous and next items.'
Add default value, please

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/pagination/pagination.ui_patterns.yml
>        preview: false
Not necessary, its value is false by default. To be checked at markup test.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/progress/progress.ui_patterns.yml
> +      description: 'Animation on striped bar.'
Add value by default, please

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/progress/progress.ui_patterns.yml
> +      preview: 0
If default value is zero, not necessary

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/progress/progress.ui_patterns.yml
> +      description: 'Minimum state of progress bar. 0 by default. '
```suggestion
      description: 'Minimum state of progress bar. 0 by default.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/progress/progress.ui_patterns.yml
> +      description: 'Text inside the progress bar'
```suggestion
      description: 'Text inside the progress bar.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/progress/progress.ui_patterns.yml
> +      description: 'Optional description text below the progress bar'
```suggestion
      description: 'Optional description text below the progress bar.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +  description: 'For more information: https://v5.getbootstrap.com/docs/5.0/content/typography/#table'
```suggestion
  description: 'For more information visit: https://v5.getbootstrap.com/docs/5.0/content/typography/#table'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +  description: 'For more information: https://v5.getbootstrap.com/docs/5.0/content/typography/#table'
Maybe we can add some simple text before the part "For more info..."  just to say like 'Pattern to show a table'.

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +      description: 'Add zebra-striping to any table row within the <tbody>.'
Add default value to description. Change to 'When enabled, adds a zebra-striping...'

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +      description: 'Enable a hover state on table rows within a <tbody>.'
Add default value to the description. Use other way of expressing: "When enabled, allows hover state..."

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +      description: 'If true, makes table more compact by cutting all cell padding in half. False by default.'
```suggestion
      description: 'When enabled, makes table more compact by cutting all cell padding in half. False by default.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +      description: 'An array with the tfoot with items with content and col-span.'
```suggestion
      description: 'An array with the table footer (tfoot) with items with content and col-span.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/table/table.ui_patterns.yml
> +      description: 'An array with the tbody with active, alignment, style and cells array with content and col-span.'
```suggestion
      description: 'An array with the table body (tbody) with active, alignment, style and cells array with content and col-span.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/timeline/timeline.ui_patterns.yml
> +      description: 'When all items are displaying, label of the button to hide them.'
```suggestion
      description: 'When all items are displayed, the label of the button to hide them.'
```

2022-01-17 13:26 UTC, abel-santos-corral commented on templates/patterns/timeline/timeline.ui_patterns.yml
> +      description: 'When there are hidden items, label of the button to expand them.'
```suggestion
      description: 'When there are hidden items, the label of the button to expand them.'
```

2022-01-17 14:50 UTC, abel-santos-corral approved these changes

2022-01-21 16:01 UTC, brummbar requested changes

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/nav/nav.ui_patterns.yml
> -  description: 'https://v5.getbootstrap.com/docs/5.0/components/navs/'
We drop this pattern now.

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/offcanvas/offcanvas.ui_patterns.yml
> +  description: 'Hidden sidebar with activation. For more information visit: https://getbootstrap.com/docs/5.0/components/offcanvas/'
Remove all the information about button and add a single "toggle" field. Type array, label "Toggle button", description "An optional button pattern definition that will allow to show/hide the offcanvas."
In the twig file we check. If the "toggle" variable is not empty, we merge a sensible default button with the values passed by the user.

We then do something like this:
```
{% if toggle is not empty %}
  {% set _toggle_attributes = toggle.attributes|default({}) %}
  {% set _toggle_attributes = _toggle_attributes|merge({
    'data-bs-toggle': 'offcanvas',
    'data-bs-target': '#' ~  offcanvas_id,
    'aria-controls': offcanvas_id
  }, true) %}
  {% set _toggle = toggle|merge({
    attributes: _toggle_attributes
  }) %}
  {{ pattern('button', _toggle) }}
{% endif %}
```

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/pagination/pagination.ui_patterns.yml
>      enable_icon:
Not a super fan of this, but let's put at least `enable_icons` plural.

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/progress/progress.ui_patterns.yml
> +      description: 'Maximum state of progress bar. 100 by default.'
I would place these together with progress.

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/progress/progress.ui_patterns.yml
>      bar_label:
Maybe "text" for this?

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/table/pattern-table.html.twig
> + * Table pattern.
If not used in ucpkn, we drop this.

2022-01-21 16:01 UTC, brummbar commented on templates/patterns/timeline/pattern-timeline.html.twig
> +  'toggle_expanded': _toggle_expanded,
```suggestion
  'toggle_collapsed': toggle_collapsed|default('Show more %d items'|t) ,
  'toggle_expanded': toggle_expanded|default('Hide %d items'|t),
```
By the way, we need to add "label" to the name, or it seems a boolean variable. "collapse_button_label" and "expand_button_label" i think they are better.

2022-01-23 17:46 UTC, escuriola commented on templates/patterns/nav/nav.ui_patterns.yml
> -  description: 'https://v5.getbootstrap.com/docs/5.0/components/navs/'
This pattern is being used in several places and in other patterns. Are you sure @brummbar

2022-01-25 14:51 UTC, brummbar approved these changes

2022-01-25 16:10 UTC, merged