OEL-779: Card pattern review.
openeuropa/oe_bootstrap_theme pull request #158
Opened 2022-01-14 12:05 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-779

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card/card.ui_patterns.yml
>        preview: false
Not necessary, is false by default.

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card/card.ui_patterns.yml
> +      description: 'Card content'
```suggestion
      description: 'Card content.'
```

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card/card.ui_patterns.yml
> +      description: 'Card header content'
```suggestion
      description: 'Card header content.'
```

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card_layout/card_layout.ui_patterns.yml
> +      description: 'Use the Bootstrap grid system and its classes to control how many grid columns (wrapped around your cards) you show per row.'
```suggestion
      description: 'Use the Bootstrap grid system and its classes to control how many grid columns (wrapped around your cards) are shown per row.'
```

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card_layout/card_layout.ui_patterns.yml
> +      label: 'Grid columns:'
```suggestion
      label: 'Grid columns'
```

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card_layout/card_layout.ui_patterns.yml
>          1: 1
```suggestion
        1: '1 (default)'
```

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card_layout/card_layout.ui_patterns.yml
>        preview: false
Not necessary

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card_layout/card_layout.ui_patterns.yml
> +      description: 'An array of card patterns items.'
I think is 'An array of card pattern items.' to be checked if it's like that.

2022-01-17 14:13 UTC, abel-santos-corral commented on templates/patterns/card_layout/pattern-card-layout.html.twig
> +{% endfor %}
Could be good a blank line here.

2022-01-25 07:46 UTC, brummbar requested changes

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
> +        white: 'white'
Dropperoo.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
> +        position: 'top'
Let's just support path and alt.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
> +      type: array
See date_block pattern.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/pattern-card.html.twig
> +{% if title is not empty %}
Let's add {% spaceless %} here and endspaceless at the end of this template to drop some extra white spacing.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/pattern-card.html.twig
> +    'content': text,
Let's use div as 'tag', as users could pass two <p> as content, and it's not allowed in html.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/pattern-card.html.twig
>    'extra_classes_footer': extra_classes_footer,
Aren't these gone?

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
>      card_header:
We are in the card, so 'header' is enough. Same for footer.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
>      horizontal:
Should we call it orientation, like we did around? or keep it as boolean?
Since we are here and there are no other settings left, move it as field already.

2022-01-25 07:46 UTC, brummbar commented on templates/patterns/card_layout/pattern-card-layout.html.twig
> +  {% set _item = _item|merge({
We need to add all the same tags that we have in the card one, so that the same result comes out. So m2 margin, div, etc.

2022-01-25 18:25 UTC, brummbar requested changes

2022-01-25 18:25 UTC, brummbar commented on templates/patterns/card_layout/pattern-card-layout.html.twig
> +    }
Almost, now if we don't have one of these entries, the wrapper shows up anyway. We need to add also the same if statements.

2022-01-25 18:25 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
>      date:
The date looks horrible, let's remove it for now and we will add it when it's styled properly.

2022-01-25 18:25 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
>      image:
I've noticed this `oe_bootstrap_theme_preprocess_pattern_card` but I don't think we need it anymore.

2022-01-26 16:37 UTC, brummbar approved these changes

2022-01-26 16:41 UTC, abel-santos-corral approved these changes

2022-01-26 16:41 UTC, merged