OEL-1049: [BE] [BCL 0.18.0] Inpage navigation
openeuropa/oe_bootstrap_theme pull request #162
Opened 2022-01-19 14:23 UTC by abel-santos-corral

Jira issue(s):
- [OEL-1049](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1049)

2022-02-03 16:24 UTC, escuriola requested changes

2022-02-03 16:24 UTC, escuriola commented on templates/patterns/inpage_navigation/inpage_navigation.ui_patterns.yml
> +    id_inpage:
Remove this. It's generated on the preprocess.

2022-02-03 16:50 UTC, escuriola requested changes

2022-02-03 16:50 UTC, escuriola commented on templates/patterns/inpage_navigation/inpage_navigation.ui_patterns.yml
> +  settings:
This is set always as true, do we really need this settings?

2022-02-04 11:18 UTC, escuriola approved these changes

2022-02-04 11:27 UTC, brummbar approved these changes

2022-02-04 12:55 UTC, merged