OEL-1160: Header refactor. Add logos from BCL and disable collapse in navbar
openeuropa/oe_bootstrap_theme pull request #181
Opened 2022-02-16 17:34 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1160

2022-02-18 13:13 UTC, drishu requested changes

2022-02-18 13:13 UTC, drishu commented on bcl-builder.config.js
> +      from: ["node_modules/@openeuropa/bcl-theme-default/logos/eu/condensed-version/**"],
we need to add the new assets/logo folder to gitignore

2022-02-18 13:13 UTC, drishu commented on templates/patterns/navbar/navbar.ui_patterns.yml
> +      description: 'The breakpoint at which the menu will be shown as expanded. For earlier breakpoints, it will be shown after clicking a toggle button. Must be a valid breakpoint class (sm, md, lg)
lets add preview: 'lg', I can toggle the mobile in my browser, its nice to see it collapse then

2022-02-22 07:55 UTC, drishu approved these changes

2022-02-22 08:49 UTC, abel-santos-corral approved these changes

2022-02-22 08:51 UTC, merged