OEL-1189: Remove settings from description list.
openeuropa/oe_bootstrap_theme pull request #183
Opened 2022-02-21 14:34 UTC by escuriola

Jira issue(s):
- [D8AGE-???](https://webgate.ec.europa.eu/CITnet/jira/browse/D8AGE-???)

2022-02-21 17:02 UTC, drishu approved these changes

2022-02-21 17:04 UTC, drishu requested changes

2022-02-21 17:04 UTC, drishu commented on tests/src/Kernel/fixtures/markup_rendering_patterns/description_list.yml
> +        orientation: 'horizontal'
this is breaking the yml it seems

2022-02-21 18:44 UTC, drishu approved these changes

2022-02-23 13:04 UTC, abel-santos-corral approved these changes

2025-06-09 13:34 UTC, closed without merging