OEL-755: Listing refactor & paragraph
openeuropa/oe_bootstrap_theme pull request #191
Opened 2022-02-24 16:00 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-755

2022-03-07 16:29 UTC, donquixote commented on modules/oe_bootstrap_theme_helper/src/TwigExtension/TwigExtension.php
> +      }
So we are changing the signature of this bcl_card_list twig function:
We now support a key `$item['url']`. But this key, if provided, must be a `Drupal\Core\Url` object.
I don't oppose this, but I find it odd that we introduce this change in such a sneaky way, as part of a "fix tests" commit.

2022-03-16 08:06 UTC, drishu requested changes

2022-03-16 08:06 UTC, drishu commented on templates/patterns/listing/listing.ui_patterns.yml
> +  description: 'Listing used for the List item block.'
```suggestion
  description: 'Listing of cards.'
```

2022-03-16 08:06 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +      'path' => file_url_transform_relative(file_create_url($card_image_file->getFileUri())),
check if the services from here https://www.drupal.org/node/2940031 are avail in D9.2, if yes replace

2022-03-16 08:06 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    $card_title = $card_paragraph->get('field_oe_title')->value;
is it worth having a dedicated variable ?

2022-03-16 08:06 UTC, drishu commented on modules/oe_bootstrap_theme_helper/src/TwigExtension/TwigExtension.php
> +        if (!empty($item['url'])) {
this will always be a Url object so please check ->toString()

2022-03-16 08:06 UTC, drishu commented on tests/src/Kernel/Paragraphs/ListingParagraphsTest.php
> +
remove newline

2022-03-16 08:06 UTC, drishu commented on tests/src/Kernel/Paragraphs/ListingParagraphsTest.php
> +      'created' => 1636977600,
is this needed?

2022-03-16 08:06 UTC, drishu commented on tests/src/Kernel/Paragraphs/ListingParagraphsTest.php
> +    $this->assertCount(6, $crawler->filter('div.col-md-3.col-lg-2.rounded'));
you dont need to assert the .rounded, we just assert cards are present, no need to check the left right cols and all these candy classes, card.body is enough

2022-03-16 08:06 UTC, drishu commented on tests/src/Kernel/Paragraphs/ListingParagraphsTest.php
> +      $paragraph = Paragraph::create([
you don't need all this, you'r not asserting the paragraph content in this test, and that is ok, you don't need date, you dont need image, you dont need most, add just minimal and use a random function instead where needed

2022-03-16 11:20 UTC, donquixote commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +      'path' => file_url_transform_relative(file_create_url($card_image_file->getFileUri())),
They are not.
I already tried this and then had to go back.

2022-03-16 11:35 UTC, donquixote commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +    $card_title = $card_paragraph->get('field_oe_title')->value;
No. Not in this case.
It is a leftover from when we built this as a link conditionally, instead of passing 'url' as a separate array key.

2022-03-16 11:50 UTC, drishu approved these changes

2022-03-16 12:19 UTC, abel-santos-corral approved these changes

2022-03-16 12:23 UTC, merged

2022-07-18 14:59 UTC, donquixote commented on modules/oe_bootstrap_theme_helper/src/TwigExtension/TwigExtension.php
> +        if (!empty($item['url'])) {
Now fixed in https://github.com/openeuropa/oe_bootstrap_theme/pull/250

2022-07-18 15:00 UTC, donquixote commented on templates/patterns/listing/listing.ui_patterns.yml
> +  description: 'Listing used for the List item block.'
Fixed in https://github.com/openeuropa/oe_bootstrap_theme/pull/250.

2022-07-18 15:01 UTC, donquixote commented on modules/oe_bootstrap_theme_helper/src/TwigExtension/TwigExtension.php
> +      }
nothing we can do about it now..

2022-07-18 15:17 UTC, donquixote commented on tests/src/Kernel/Paragraphs/ListingParagraphsTest.php
> +    $this->assertCount(6, $crawler->filter('div.col-md-3.col-lg-2.rounded'));
Done in https://github.com/openeuropa/oe_whitelabel/pull/163

2022-07-18 15:22 UTC, donquixote commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module
> +      'path' => file_url_transform_relative(file_create_url($card_image_file->getFileUri())),
no longer applies, we are using ImageValueObject::fromImageItem() now

2022-07-18 15:24 UTC, donquixote commented
Remaining comments are addressed in https://github.com/openeuropa/oe_whitelabel/pull/163 and https://github.com/openeuropa/oe_bootstrap_theme/pull/250