OEL-1160: Set navbar to default variant menu navigation.
openeuropa/oe_bootstrap_theme pull request #196
Opened 2022-03-08 08:28 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1160

2022-03-09 18:51 UTC, brummbar requested changes
Let's add test assertions so that we check that navbar is on only for the default variant.

2022-03-10 16:44 UTC, brummbar approved these changes, later dismissed

2022-03-11 16:04 UTC, brummbar approved these changes

2022-03-14 08:40 UTC, drishu commented on templates/overrides/menu/menu--main.html.twig
> +  'variant': 'navbar',
We should set here class 'me-auto' and ditch the wrapping div in pattern-navbar.
If we do that and we override the block template for the main menu to remove the nav wrapper then we would have the needed structure in navbar

2022-03-14 08:40 UTC, drishu approved these changes

2022-03-14 09:08 UTC, merged