OEL-1307: Update to BCL 0.20.0
openeuropa/oe_bootstrap_theme pull request #199
Opened 2022-03-09 17:29 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1307

2022-03-14 17:31 UTC, brummbar requested changes
Just a very small change, all seems to work well.

2022-03-14 17:31 UTC, brummbar commented on templates/patterns/alert/alert.ui_patterns.yml
> +      preview: 'lock'
Why this change?

<img width="146" alt="image" src="https://user-images.githubusercontent.com/8488617/158226686-d3efc99f-5705-490a-a153-63ca9b35bf51.png">

Can we pick a more meaningful icon.

2022-03-21 12:37 UTC, drishu approved these changes, later dismissed

2022-03-28 14:35 UTC, drishu approved these changes

2022-03-28 15:04 UTC, brummbar approved these changes

2022-03-29 05:30 UTC, merged