OEL-1280: Copy and rename paragraph submodule from oe_bootstrap_theme
openeuropa/oe_bootstrap_theme pull request #201
Opened 2022-03-11 15:25 UTC by abel-santos-corral

Jira issue(s):
- [OEL-1280](https://citnet.tech.ec.europa.eu/CITnet/jira/projects/OEL/issues/OEL-1280)

2022-03-16 12:26 UTC, drishu requested changes
I will double check that all files are removed (test and whatever else related after the rebase, makes no sense now

2022-03-16 12:26 UTC, drishu commented on modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.info.yml
> -name: OpenEuropa Bootstrap Theme Paragraphs
you can't delete this file
```
[error]  OpenEuropa Bootstrap Theme Paragraphs is required if OpenEuropa Paragraphs is 
enabled.
 
 [error]   (Currently using Missing or invalid module The following module is marked as installed in the core.extension 
configuration, but it is missing:
```
just delete the config_devel from here

2022-03-17 11:57 UTC, drishu requested changes
Move also the paragraphs references in the README, and oe_bootstrap_theme_helper_requirements

2022-03-17 13:08 UTC, drishu requested changes
found field--entity-reference-revisions--paragraph.html.twig

2022-03-17 16:45 UTC, donquixote approved these changes
Looks good to me now.

2022-03-17 16:48 UTC, drishu approved these changes

2022-03-17 16:57 UTC, merged