OEL-1322: PHP 8.0 Upgrade.
openeuropa/oe_bootstrap_theme pull request #209
Opened 2022-03-17 15:03 UTC by escuriola

Jira issue(s):
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1322

2022-03-18 15:17 UTC, brummbar requested changes

2022-03-18 15:17 UTC, brummbar commented on .drone.yml
> +      - COMPOSERVER=--2
We removed this already recently, no need to readd.

2022-03-21 15:39 UTC, brummbar approved these changes, later dismissed

2022-03-22 10:16 UTC, donquixote commented
Seem good to me.

For the changes in composer.json, we need to make sure to clean up if we no longer need these packages. E.g. token is only needed for ui_patterns_settings, and perhaps we will remove this in the future?
But this should not block us.

I also don't know if there are any yet undiscovered problems for PHP 8.0.
But we can always create follow-up issues.

2022-03-22 10:17 UTC, donquixote approved these changes, later dismissed

2022-03-22 10:23 UTC, donquixote commented
Btw the README.md still talks about PHP 7.3 as a minimum version.
But I think we should deal with this in a separate issue.

2022-03-22 10:32 UTC, donquixote approved these changes

2022-03-22 10:52 UTC, brummbar approved these changes

2022-03-22 10:52 UTC, merged