OEL-1283: Document upgrade for paragraphs move.
openeuropa/oe_bootstrap_theme pull request #210
Opened 2022-03-21 19:55 UTC by donquixote

[D8AGE-1283](https://webgate.ec.europa.eu/CITnet/jira/browse/D8AGE-1283)

2022-03-31 10:20 UTC, drishu requested changes

2022-03-31 10:20 UTC, drishu commented on README.md
> +#### Paragraphs migration
maybe "Upgrade to version x"

2022-03-31 10:20 UTC, drishu commented on README.md
> +Paragraphs-related theming and functionality has been moved from the [OpenEuropa Bootstrap base theme](https://github.com/openeuropa/oe_whitelabel) to [OpenEuropa Whitelabel](https://github.com/opene
the OEBT link is wrong

2022-03-31 10:20 UTC, drishu commented on README.md
> +The `oe_bootstrap_theme_paragraphs` module has been reduced to a skeleton. It will be disabled as part of an update hook in `oe_bootstrap_theme_helper`. It will be fully removed in future versions.
```suggestion
The `oe_bootstrap_theme_paragraphs` has been reduced to an empty module. It will be disabled as part of an update hook in `oe_bootstrap_theme_helper`. It will be fully removed in future versions.
```

2022-03-31 12:46 UTC, brummbar requested changes

2022-03-31 12:46 UTC, brummbar commented on README.md
> +If you are _not_ using `openeuropa/oe_whitelabel`, but still want theming for paragraphs from `oe_paragraphs`, you need to replicate this functionality in custom code.
Let's drop this line, as it's implied by the move and the suggestion is not needed.

2022-03-31 12:46 UTC, brummbar commented on README.md
> +Target release: You can upgrade directly to the version that contains this README.md.
What does this mean? If there's nothing to do, then the line doesn't need to exist.

2022-03-31 12:59 UTC, brummbar commented
Let's write here only that support for paragraphs has been moved to oe_whitelabel from version X on. If the user needs it, they should follow the update steps in whitelabel readme.

2022-03-31 13:17 UTC, donquixote commented on README.md
> +Target release: You can upgrade directly to the version that contains this README.md.
I was thinking too far ahead.
For now we can remove this.
If in the future we need to have an upgrade in two steps, this would become "upgrade to version x first".

2022-04-01 11:13 UTC, donquixote commented on README.md
> +Configuration and data for these paragraph types that is already in your database will be preserved in this uninstall operation.
Is this minimal enough or should we also drop the above two paragraphs?

2022-04-01 11:14 UTC, donquixote commented on README.md
> +Configuration and data for these paragraph types that is already in your database will be preserved in this uninstall operation.
It is stuff they can figure out.

2022-04-01 13:34 UTC, drishu approved these changes
would have been nice to have a link on "there" (last word) that links to the upgrade instructions, but since a sentence above there is a link to whitelabel its not a blocker 4 me

2022-04-01 15:41 UTC, brummbar approved these changes

2022-04-01 15:43 UTC, merged