OEL-1382: Allow drupal alters in menu links.
openeuropa/oe_bootstrap_theme pull request #241
Opened 2022-05-18 14:23 UTC by escuriola

Jira issue(s):
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1382

2022-05-21 16:46 UTC, claudiu-cristea requested changes

2022-05-21 16:46 UTC, claudiu-cristea commented on includes/menu.inc
> +      'url' => $item['url'],
This needs to be `'url' => $url`, I guess

2022-05-21 16:46 UTC, claudiu-cristea commented on includes/menu.inc
> +    ] + $passed_attributes;
What if `$passed_attributes` already contains a `class` attribute? Wouldn't that be overridden here?

2022-05-21 16:46 UTC, claudiu-cristea commented on includes/menu.inc
> +        'url' => $sub_item['url'],
Same. I think we should assign `$url` because it might be different.

2022-05-21 16:46 UTC, claudiu-cristea commented on includes/menu.inc
> +      'link' => (new Link($item['title'], $item['url']))->toRenderable(),
Should pass `$url` rather than `$item['url']`.

2022-05-21 16:46 UTC, claudiu-cristea commented on includes/menu.inc
> +        'link' => (new Link($sub_item['title'], $sub_item['url']))->toRenderable(),
Should pass `$url` rather than `$item['url']`.

2022-05-21 16:46 UTC, claudiu-cristea commented
Certainly, this needs tests

2022-09-01 15:21 UTC, drishu requested changes
Personally i agree with the idea of not having a template for it, its just that there is some logic in the template that makes it look the way BCL needs it, we will have to move that also into the preprocess

2022-09-01 15:21 UTC, drishu commented on includes/menu.inc
> +        $pattern_item['items'][$key_sub_item] = $get_pattern_item[$sub_item];
```
$get_pattern_item($sub_item);
```
we cant use anonymous function as an array because they are implemented as Closure classes

2022-09-01 15:21 UTC, drishu commented on includes/menu.inc
> +    $class[] = 'nav-link';
like this submenu items receive the nav-link class which throws off the design of it,
its ok to remove it, the nav-link class is re-attached in the navigation bcl to the correct items.

2022-09-01 15:21 UTC, drishu commented on includes/menu.inc
> -    $submenu['attributes'] = new Attribute(['class' => 'nav-link']);
and then if we remove 'nav-link' from prepare_url then we have to keep this

2022-09-01 15:21 UTC, drishu commented on includes/menu.inc
> +        'link' => TRUE,
this is what we found in netlify at the time, don't know if this needs to be set and TRUE (or something that equivalates to true, like the object set in prepare_url), but with the new setup it does not seem needed anymore here.
I did look into it and could not find any usage of the item.link in the bcl templates.

2022-09-06 08:01 UTC, drishu reviewed
We will follow up with a different direction, see ticket

2022-09-06 08:01 UTC, closed without merging