OEL-1418: Remove obsolete paragraphs requirements from oe_bootstrap_theme
openeuropa/oe_bootstrap_theme pull request #243
Opened 2022-05-20 13:40 UTC by escuriola

Jira issue(s):
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1418

2022-05-25 09:18 UTC, drishu requested changes

2022-05-25 09:18 UTC, drishu commented on README.md
> +
above this section, add "Upgrade to 1.0.0-beta2"
there we explain that these composer packages are removed now and if needed, action needs to be taken.

2022-05-25 15:35 UTC, drishu requested changes

2022-05-25 15:35 UTC, drishu commented on README.md
> +The following paragraph's required components has been removed from [OpenEuropa Bootstrap base theme](https://github.com/openeuropa/oe_bootstrap_theme)
Lets use plural here
The following paragraphs required components have been ...

2022-05-25 15:35 UTC, drishu commented on README.md
> +### Upgrade to 1.0.0-beta2
Please add this above the old one

2022-05-25 15:35 UTC, drishu commented on README.md
> +If any of them are required, then you must install them like any other component outside oe_bootstrap_theme.
No, rather in the sorts of: Make sure to require them if you need them.
or something like that.

2022-05-30 19:41 UTC, drishu submitted a review, later dismissed

2022-06-01 18:26 UTC, donquixote commented on README.md
> +
Perhaps we should mention that you need to upgrade to alpha8 first if you had something older than that.

2022-06-01 18:30 UTC, donquixote commented on README.md
> +The following paragraphs required components have been removed from [OpenEuropa Bootstrap base theme](https://github.com/openeuropa/oe_bootstrap_theme)
What is a "paragraphs required component"?

2022-06-01 18:34 UTC, donquixote commented on README.md
> +The following paragraphs required components have been removed from [OpenEuropa Bootstrap base theme](https://github.com/openeuropa/oe_bootstrap_theme)
As the list below is about composer packages, we should say that:
```suggestion
Dependencies to the following packages have been removed in composer.json:
```
just a proposal, feel free to improve

2022-06-02 13:08 UTC, escuriola commented on README.md
> +
Has sense? I'm reading the upgrade to 1.0.0-beta2 section, and the requirements to to the previous version is inherent...

2022-06-02 13:16 UTC, donquixote commented on README.md
> +
The point is you will need a separate deployment.
Although, maybe this is only relevant once we fully remove the oe_bootstrap_theme_paragraphs module.

2022-06-02 13:16 UTC, donquixote commented on README.md
> +
@drishu thoughts? ^

2022-06-03 12:13 UTC, donquixote commented on README.md
> +
I tested the upgrade path from < alpha8.
There are problems, but they are fully covered by the comment that you already added here.
We will need to add another line later if/when we actually remove oe_bootstrap_theme_paragraphs.
So ok for now :)

2022-06-03 12:13 UTC, donquixote approved these changes

2022-06-03 12:48 UTC, drishu approved these changes

2022-06-03 12:59 UTC, merged