OEL-1995: Upgrade to BCL 0.27.0
openeuropa/oe_bootstrap_theme pull request #267
Opened 2022-09-01 16:38 UTC by brummbar

2022-10-06 12:32 UTC, drishu requested changes
I also noticed inpage navigation is not working

2022-10-06 12:32 UTC, drishu commented on kits/default/package.json
> +    "@openeuropa/bcl-builder": "0.25.1",
Lets use the same 28.1

2022-10-06 12:32 UTC, drishu commented on docker-compose.yml
> +      - NODE_ENV=${NODE_ENV:-''}
Can you give me a bit on info, the commit message should also be a bit more descriptive. 
`:-` evaluates to use `''` if NODE_ENV is unset or empty, but we give an empty string as default, would `-` (use '' if NODE_ENV is unset) work ?

2022-10-06 15:46 UTC, brummbar commented on docker-compose.yml
> +      - NODE_ENV=${NODE_ENV:-''}
We'll replace with `-`  only as it's the same operation done by Docker: provides an empty string as fallback only when the variable is not defined at all.

2022-10-06 16:52 UTC, brummbar commented
Fixed the offcanvas, for which I reviewed the updates back in the days but forgot to bring them. The inpage navigation is broken so I'll create an issue for it.

2023-01-30 09:13 UTC, drishu approved these changes

2023-01-30 09:13 UTC, merged