OEL-1915: Support date in card pattern.
openeuropa/oe_bootstrap_theme pull request #291
Opened 2022-12-19 09:41 UTC by drishu

2022-12-19 10:00 UTC, drishu commented on tests/src/PatternAssertion/CardPatternAssert.php
> +      $day_month .= ' - ' . $expected['end_day'] . '      ' . $expected['end_month'];
I don't want to do extra processing here nor patch the template just for this strange looking extra space

2022-12-20 14:25 UTC, brummbar requested changes

2022-12-20 14:25 UTC, brummbar commented on tests/src/PatternAssertion/CardPatternAssert.php
> +      $image_div = $crawler->filter('.row .col-md-3 img.card-img-top');
Since the assertions are the same, can we just determine the selector in the if() ?

2022-12-20 14:25 UTC, brummbar commented on tests/src/PatternAssertion/CardPatternAssert.php
> +    // @todo Use dedicated pattern assert once we re-work date_plock pattern.
date_block

2022-12-20 14:25 UTC, brummbar commented on tests/src/PatternAssertion/CardPatternAssert.php
> +      $day_month .= ' - ' . $expected['end_day'] . '      ' . $expected['end_month'];
But it's too risky like this unfortunately, we need to clean it up.

2022-12-20 14:25 UTC, brummbar commented on tests/src/PatternAssertion/CardPatternAssert.php
> +  protected function getBaseItemClass(string $variant): string {
Do we really need this separate? It's only used once.

2023-01-06 15:03 UTC, brummbar requested changes
All good, just this documentation change.

2023-01-06 15:03 UTC, brummbar commented on templates/patterns/card/card.ui_patterns.yml
> +      description: 'Date for card. Optional.'
I didn't remember the ticket and it took me a while to remember how to use this. It's not really an object, it's an associative array, let's put some info in here. At least let's write that it uses the same parameters of the bcl date-block template.

2023-01-12 16:49 UTC, brummbar approved these changes

2023-01-12 16:49 UTC, merged