OEL-2595: Fixed overlap of toolbar.
openeuropa/oe_bootstrap_theme pull request #379
Opened 2024-02-01 14:11 UTC by tibi2303

Jira issue(s):
- [D8AGE-???](https://webgate.ec.europa.eu/CITnet/jira/browse/D8AGE-???)

2024-02-02 17:26 UTC, brummbar requested changes

2024-02-02 17:26 UTC, brummbar commented on resources/sass/overrides/_toolbar.scss
> +    z-index: 61;
Can't we do the opposite, and raise the offcanvas/modal?

2024-02-14 11:18 UTC, tibi2303 commented on resources/sass/overrides/_toolbar.scss
> +    z-index: 61;
done, francesco. I was thinking to not touch bs z-index but I've tested it and it seems these are the only places where they would overlap.

2024-02-19 17:08 UTC, brummbar approved these changes

2024-02-19 17:29 UTC, merged