OEL-2770: Changed actions label for gallery.
openeuropa/oe_bootstrap_theme pull request #394
Opened 2024-05-07 13:37 UTC by tibi2303

Jira issue(s):
- [D8AGE-???](https://webgate.ec.europa.eu/CITnet/jira/browse/D8AGE-???)

2024-05-14 07:47 UTC, drishu requested changes
please add Julien as author as he provided the patch

2024-05-14 11:09 UTC, tibi2303 commented
@drishu changed the author.

2024-05-14 16:28 UTC, brummbar approved these changes

2024-05-21 16:48 UTC, drishu approved these changes

2024-05-22 14:36 UTC, merged