FRONT-2441: Accordion Pattern.
openeuropa/oe_bootstrap_theme pull request #41
Opened 2021-08-12 14:24 UTC by tibi2303

Jira issue(s):
- [D8AGE-???](https://webgate.ec.europa.eu/CITnet/jira/browse/D8AGE-???)

2021-08-27 14:50 UTC, drishu requested changes
we need to change includes/paragraphs.incL37 from body to content. The item content is not showing.

2021-09-03 07:29 UTC, Maxfire submitted a review, later dismissed
reviewed and approved.

2021-09-07 09:52 UTC, drishu approved these changes

2021-09-07 09:55 UTC, Maxfire approved these changes
approved

2021-09-07 09:55 UTC, merged