FRONT-2432: Blockquote Pattern.
openeuropa/oe_bootstrap_theme pull request #43
Opened 2021-08-12 14:29 UTC by tibi2303

2021-08-27 14:40 UTC, drishu requested changes
we also need to update templates/paragraphs/paragraph--oe-quote.html.twig to send parameters quote, attribution, cite and alignement

2021-08-27 14:40 UTC, drishu commented on templates/patterns/blockquote/pattern-blockquote.html.twig
> +} %}
add a newline

2021-09-02 09:45 UTC, Maxfire approved these changes, later dismissed
Looks good and working nicely. Greetings.

2021-09-03 09:54 UTC, drishu approved these changes

2021-09-03 09:56 UTC, cmarcmar commented
Looks good, working as expected.

2021-09-03 09:57 UTC, cmarcmar approved these changes

2021-09-03 09:57 UTC, merged