FRONT-2440: Breadcrumb Pattern.
openeuropa/oe_bootstrap_theme pull request #44
Opened 2021-08-12 14:34 UTC by tibi2303

2021-08-27 13:44 UTC, drishu requested changes
I made some tests and was thinking to add a Kernel rendering test, but that needs to be discussed with tech leads, so lets implement just this for now.

Please add `- "bcl"` under `file_scan_ignore_directories` in runner.dist.yml until https://github.com/openeuropa/oe_bootstrap_theme/issues/61 is solved.

2021-08-27 13:44 UTC, drishu commented on templates/overrides/navigation/breadcrumb.html.twig
>  {% if breadcrumb %}
_breadcrumb_links

2021-08-27 13:44 UTC, drishu commented on templates/overrides/navigation/breadcrumb.html.twig
>      'items': breadcrumb
_breadcrumb_links

2021-09-02 10:13 UTC, Maxfire approved these changes, later dismissed
Reviewed and working

2021-09-09 09:28 UTC, cmarcmar approved these changes

2021-09-09 09:33 UTC, Maxfire approved these changes
approved :+1:

2021-09-09 09:33 UTC, drishu approved these changes

2021-09-09 09:34 UTC, merged