OEL-3503: Support slim select V2
openeuropa/oe_bootstrap_theme pull request #452
Opened 2024-12-09 09:31 UTC by piotrsmykaj

Jira issue(s):
- [OEL-3503](https://webgate.ec.europa.eu/CITnet/jira/browse/OEL-3503)

2025-01-13 17:16 UTC, drishu requested changes
we also need to use a dev release of the BCL branch to see it all in action

2025-01-13 17:16 UTC, drishu commented on bcl-builder.config.js
> +      to: path.resolve(outputFolder, "assets"),
I dont understand why we copy the js into assets instead of assets/js

2025-01-28 08:44 UTC, piotrsmykaj commented on bcl-builder.config.js
> +      to: path.resolve(outputFolder, "assets"),
@drishu it's a way to copy the JS folder content _and subdirectories_ into the assets/js. Today I rebased the branch because slim select 2 was included in BCL 1.8.0, released a day after my commit, so now you can pull the latest changes on the branch and check that the JS directory has JS files and slim-select-2 directory with slim select js file.

2025-02-03 13:18 UTC, drishu approved these changes, later dismissed

2025-02-03 15:54 UTC, drishu commented on bcl-builder.config.js
> +      to: path.resolve(outputFolder, "assets"),
The correct tag for now should be [0.3501.202412051700](https://www.npmjs.com/package/@openeuropa/bcl-bootstrap/v/0.3501.202412051700)

2025-02-03 17:55 UTC, tibi2303 commented on bcl-builder.config.js
> +      to: path.resolve(outputFolder, "assets"),
@drishu I made a correct prerelease now: 0.3501.202502031900

Please use this version. In 1.8.0 the slim-select-2 should not be available. I made a release 1.8.2 which corrects this.

2025-02-06 12:35 UTC, piotrsmykaj commented on bcl-builder.config.js
> +      to: path.resolve(outputFolder, "assets"),
@drishu there is a newer version done by Tiberiu, with fixed style: 0.3501.202502052130

2025-02-06 13:11 UTC, drishu submitted a review, later dismissed

2025-02-10 07:49 UTC, drishu approved these changes, later dismissed

2025-03-04 14:23 UTC, drishu approved these changes

2025-03-04 14:24 UTC, merged