OEL-3569: Changed dropdown trigger from span to anchors for accessibility.
openeuropa/oe_bootstrap_theme pull request #453
Opened 2024-12-11 17:24 UTC by tibi2303

2025-02-07 16:04 UTC, drishu commented on src/MenuPreprocess.php
> +      $trigger = $this->menuLink([
this changes the tag from span to anchor, this could be a breaking change, isn't there a css solution we could use?

2025-02-07 16:05 UTC, drishu requested changes
please create a BCL dev release so we can also see the other changes

2025-02-28 00:45 UTC, tibi2303 commented on src/MenuPreprocess.php
> +      $trigger = $this->menuLink([
I changed the approach, I checked on oesa that everything it's working now.

What it's happening here is that because of bclLink process of links, the dropdown triggers that does not have a path are rendered as a span.  I was thinking at first to sustain this behaviour on bcl but it was double triggering because it already had data-bs-toggle attribute. I think the current approach will for sure only target the nav items that have a below and does not have link in order to be rendered as a link and not span because of hardcoding # as path

2025-03-01 09:19 UTC, drishu submitted a review, later dismissed

2025-03-11 15:32 UTC, drishu approved these changes

2025-03-11 15:44 UTC, merged