FRONT-2475: Dropdown pattern.
openeuropa/oe_bootstrap_theme pull request #50
Opened 2021-08-24 14:56 UTC by escuriola

2021-09-24 14:55 UTC, abel-santos-corral submitted a review, later dismissed

2021-09-29 12:41 UTC, drishu requested changes
just this small thing and rebase pls

2021-09-29 12:41 UTC, drishu commented on templates/patterns/dropdown/pattern-dropdown.html.twig
> + * Dropdown component.
```suggestion
 * Dropdown pattern.
```

2021-09-29 13:48 UTC, escuriola commented on templates/patterns/dropdown/pattern-dropdown.html.twig
> + * Dropdown component.
I tried to adapt but I think is not possible. Main reasons: 

- The button for instance sometimes is outlined but at dropdown we cannot set this variant, 
- Links are rendered link objects, so is not possible to pass as variable

2021-09-29 14:05 UTC, drishu approved these changes

2021-09-29 14:06 UTC, abel-santos-corral approved these changes

2021-09-29 14:07 UTC, merged