FRONT-2477: Icon pattern.
openeuropa/oe_bootstrap_theme pull request #52
Opened 2021-08-25 07:30 UTC by escuriola

2021-09-08 14:29 UTC, drishu approved these changes

2021-09-08 14:33 UTC, abel-santos-corral approved these changes, later dismissed
Approved

2021-09-08 14:34 UTC, drishu requested changes
Lets w8 4 green build

2021-09-09 07:31 UTC, drishu approved these changes

2021-09-09 07:34 UTC, Maxfire approved these changes
approved :+1:

2021-09-09 07:37 UTC, merged