FRONT-2477: List group pattern.
openeuropa/oe_bootstrap_theme pull request #53
Opened 2021-08-25 07:50 UTC by escuriola

2021-08-30 08:41 UTC, GilNovacomm reviewed
While the pattern works as designed a few points should be reviewed:
The border around the component is missing.
Passing items to the pattern itself does not work so a pattern override template for this component needs to be implemented to preprocess the necessary variables.
There is no **List group** paragraph, **Listing item block** is an existing paragraph if the later is the one this pattern is supposed to theme then it's name it not obvious and should be corrected.

2021-09-22 13:16 UTC, drishu requested changes

2021-09-22 13:16 UTC, drishu commented on templates/patterns/list_group/list_group.ui_patterns.yml
> +      type: boolean
must be select and list the options

2021-09-23 06:54 UTC, drishu approved these changes

2021-09-23 07:01 UTC, Maxfire approved these changes
approved. :+1:

2021-09-23 07:02 UTC, merged