FRONT-2479: Modal pattern.
openeuropa/oe_bootstrap_theme pull request #54
Opened 2021-08-25 08:00 UTC by escuriola

2021-09-08 07:15 UTC, abel-santos-corral commented
Handled at https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-416

2021-09-22 06:09 UTC, drishu requested changes

2021-09-22 06:09 UTC, drishu commented on templates/patterns/modal/pattern-modal.html.twig
>    {{ pattern('button', {
what if we want to use this like we do now here https://github.com/openeuropa/oe_whitelabel/blob/1.x/templates/overrides/navigation/links--language-block.html.twig#L26 where the trigger should be a link, also we may want to use an existing link and have the modal printer somewhere else, so this is what I suggest:
lets wrap the button pattern in an if, ex `if btn_label is not empty` then the trigger can come from soemwhere else and we dont care what it is

2021-09-22 06:09 UTC, drishu commented on templates/patterns/modal/modal.ui_patterns.yml
> +    id:
id is a reserver work for the pattern, if I set this it breaks, use `modal_id` or something like that

2021-09-23 06:29 UTC, drishu approved these changes

2021-09-23 06:30 UTC, abel-santos-corral approved these changes

2021-09-23 06:32 UTC, merged