FRONT-2482: Offcanvas pattern.
openeuropa/oe_bootstrap_theme pull request #55
Opened 2021-08-25 08:57 UTC by escuriola

2021-09-06 16:08 UTC, cmarcmar submitted a review, later dismissed

2021-09-10 11:58 UTC, drishu requested changes
`Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at Fi._initializeBackDrop (js_H7mddBuJ5JP8zHJYQoO3fETpmKyHMv7XI5Wt7D5AAFo.js:274)
    at new Fi (js_H7mddBuJ5JP8zHJYQoO3fETpmKyHMv7XI5Wt7D5AAFo.js:274)
    at Function.getOrCreateInstance (js_H7mddBuJ5JP8zHJYQoO3fETpmKyHMv7XI5Wt7D5AAFo.js:274)
    at HTMLButtonElement.<anonymous> (js_H7mddBuJ5JP8zHJYQoO3fETpmKyHMv7XI5Wt7D5AAFo.js:274)
    at HTMLDocument.n (js_H7mddBuJ5JP8zHJYQoO3fETpmKyHMv7XI5Wt7D5AAFo.js:274)`

`{{ pattern('offcanvas', {
    placement: 'start',
    with_backdrop: true,
    with_trigger: true,
    title: 'Title',
    body: 'Body body',
  }) }}`

2021-09-14 10:58 UTC, drishu approved these changes

2021-09-14 11:01 UTC, GilNovacomm approved these changes
Review ok

2021-09-14 11:01 UTC, merged