FRONT-2476: Form input group created.
openeuropa/oe_bootstrap_theme pull request #73
Opened 2021-09-21 12:35 UTC by Maxfire

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-413

2021-09-22 12:06 UTC, escuriola reviewed
Also some styles missing, for instance form-required has not any special style to mark a field as required, and checkbox left-margin doesn't fit well sometimes.

2021-09-22 12:06 UTC, escuriola commented on templates/patterns/form_input/form_input.ui_patterns.yml
> +      input_type: checkbox
Not needed

2021-09-22 12:06 UTC, escuriola commented on templates/patterns/form_input/form_input.ui_patterns.yml
> +      input_type: file
Not needed

2021-09-22 12:06 UTC, escuriola commented on templates/overrides/form/input--textfield.html.twig
> +  {% set attributes = attributes.setAttribute('placeholder', 'text here')  %}
This default text should be translatable

2021-09-22 12:39 UTC, escuriola approved these changes, later dismissed

2021-09-23 07:47 UTC, drishu requested changes
- the helper text has the correct class, and even though not a div, visually its ok
- valid-feedback and invalid-feedback are handled differently in drupal so we won't touch those
- if validation error is present the message is presented on top in the messages area and the border is collored red as it should be (in netlify its not and that is a mistake I feel)

2021-09-23 07:47 UTC, drishu commented on templates/overrides/form/form-element--checkbox.html.twig
> +    switch ? 'form-check form-switch': 'form-check',
so we do this in checkbox, if needed

2021-09-23 07:47 UTC, drishu commented on templates/overrides/form/input--textfield.html.twig
> +  {%
no intend needed

2021-09-23 07:47 UTC, drishu commented on templates/overrides/form/input--textfield.html.twig
> +  {% set attributes = attributes.setAttribute('placeholder', 'text here'|t)  %}
remove this

2021-09-23 08:18 UTC, drishu approved these changes, later dismissed

2021-09-23 15:24 UTC, brummbar requested changes

2021-09-23 15:24 UTC, brummbar commented on templates/overrides/form/form-element-label.html.twig
> +  'form-label',
Nit: these are to be indented.

2021-09-23 15:24 UTC, brummbar commented on templates/overrides/form/input--textfield.html.twig
> +
Nit: Drop this empty line, it generates un unneeded empty line.

2021-09-23 15:24 UTC, brummbar commented on templates/overrides/form/input--textfield.html.twig
> + * Theme override for an 'input' #type form element.
This is not correct, this is an override for input of type textfield.

2021-09-24 09:15 UTC, brummbar approved these changes

2021-09-24 09:25 UTC, drishu approved these changes

2021-09-24 09:25 UTC, merged