Front 2490
openeuropa/oe_bootstrap_theme pull request #78
Opened 2021-09-24 07:56 UTC by Maxfire

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-426

2021-09-27 12:28 UTC, abel-santos-corral submitted a review, later dismissed
Review finished. Only added +1 row at table.ui_patterns.yml and changed the content of the three rows of the preview.

2021-09-28 18:25 UTC, escuriola requested changes

2021-09-28 18:25 UTC, escuriola commented on templates/overrides/views/views-view-table.html.twig
> +  caption: caption,
Missing table_responsive:
```suggestion
  caption: caption,
  table_responsive:  responsive ? true...
```

2021-09-28 18:25 UTC, escuriola commented on templates/overrides/views/views-view-table.html.twig
> +}) }}
Details (summary and description) also missing inside caption.

2021-09-28 18:25 UTC, escuriola commented on templates/overrides/dataset/table.html.twig
> +  caption: caption,
```suggestion
  caption: caption,
   table_responsive: true,
```

2021-09-29 09:11 UTC, escuriola commented on templates/overrides/views/views-view-table.html.twig
> +}) }}
![image](https://user-images.githubusercontent.com/6751237/135239157-bb8d8af4-f400-4d11-a5aa-c1b1e70778fb.png)

2021-09-29 10:39 UTC, Maxfire commented on templates/overrides/views/views-view-table.html.twig
> +  caption: caption,
As we checked it's already in place.

2021-09-29 10:40 UTC, Maxfire commented on templates/overrides/dataset/table.html.twig
> +  caption: caption,
same as before, it's already in place.

2021-09-29 10:57 UTC, Maxfire commented on templates/overrides/views/views-view-table.html.twig
> +}) }}
Added in the view template.

2021-10-01 12:17 UTC, drishu approved these changes

2021-10-01 12:18 UTC, escuriola approved these changes

2021-10-01 12:18 UTC, merged