OEL-474: Pattern Testing
openeuropa/oe_bootstrap_theme pull request #80
Opened 2021-09-27 09:17 UTC by escuriola

Jira issue(s):
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-474

2021-09-27 14:31 UTC, drishu requested changes

2021-09-27 14:31 UTC, drishu commented on runner.yml.dist
> +    - { task: "copy", from: "build/sites/default/default.services.yml", to: "build/sites/default/services.yml" }
we shouldn't enforce this

2021-10-01 10:19 UTC, claudiu-cristea requested changes
Only very small changes.

2021-10-01 10:19 UTC, claudiu-cristea commented on tests/Kernel/MarkupRenderingTest.php
> +   *   @endcode
This sample contains `ecl` because it was copied from there. Let's adapt more to OE Bootstrap Theme.

2021-10-01 10:19 UTC, claudiu-cristea commented on tests/Kernel/MarkupRenderingTest.php
> +    return Yaml::decode(file_get_contents(__DIR__ . '/../fixtures/markup_rendering.yml'));
As we've been discussed in the daily, let's create 2 YAML files: `markup_rendering.yml` & `markup_rendering_pattern.yml`. So, that we'll create all `'#type': pattern` in the later. Here, we need to merge them in order to return all.

2021-10-01 13:35 UTC, claudiu-cristea approved these changes

2021-10-01 13:36 UTC, Maxfire approved these changes

2021-10-01 13:36 UTC, merged