OEL-522: Drop Components module. Use ECL Twig loader
openeuropa/oe_bootstrap_theme pull request #91
Opened 2021-10-01 13:54 UTC by claudiu-cristea

2021-10-28 13:59 UTC, brummbar requested changes

2021-10-28 13:59 UTC, brummbar commented on .drone.yml
> +      - ./vendor/bin/phpunit --testdox
Is this on purpose?

2021-10-28 13:59 UTC, brummbar commented on composer.json
> +        "openeuropa/task-runner": "dev-master as 1.0.0-beta7",
Is this needed?

2021-10-28 13:59 UTC, brummbar commented on .gitignore
>  /templates/bcl
This we can drop.

2021-10-28 13:59 UTC, brummbar commented on modules/oe_bootstrap_theme_helper/tests/Kernel/BclComponentsOverrideTest.php
> +<?php
This file should be in tests/src . Let's take the chance to move also the other one (MarkupRenderingTest).

2021-10-28 13:59 UTC, brummbar commented on modules/oe_bootstrap_theme_helper/tests/Kernel/BclComponentsOverrideTest.php
> +    file_put_contents("$path/bcl-card/bcl-card.html.twig", 'Card: oe_bootstrap_theme version');
This destroys the original content of the template unfortunately. We need to resort to some other solution.

2021-10-28 13:59 UTC, brummbar commented on modules/oe_bootstrap_theme_helper/tests/Kernel/BclComponentsOverrideTest.php
> +        '#type' => 'pattern',
Maybe you can use `'#type' => 'pattern_preview'` to solve the issue of the comment above. So you don't have to pass any pattern data. Only the yaml will get more complex.

2021-10-28 14:01 UTC, claudiu-cristea commented on .drone.yml
> +      - ./vendor/bin/phpunit --testdox
I want to see which test runs at some point not only dots. In this way I can spot a failure and locate the failed test before the whole pipeline is finish.

2021-10-28 14:08 UTC, claudiu-cristea commented on composer.json
> +        "openeuropa/task-runner": "dev-master as 1.0.0-beta7",
Yes, it's for the hack in `runner.yml.dist`. Specifically, with `beta6` I'm getting:

```
Task 'exec' not supported.
```

Yeah, we need a new beta release with Task Runner, a lot of new code has accumulated in `master`.

2021-10-28 14:12 UTC, claudiu-cristea commented on modules/oe_bootstrap_theme_helper/tests/Kernel/BclComponentsOverrideTest.php
> +    file_put_contents("$path/bcl-card/bcl-card.html.twig", 'Card: oe_bootstrap_theme version');
We're not asserting here the content. The content of template is not relevant by any means. But how the templates are overriding each other it is. It's the main and the only goal of this test. Having simple content that identifies form which theme the template is coming is more important. Really, I would not change that for the sake of test assertion readability.

2021-10-28 14:28 UTC, claudiu-cristea commented on modules/oe_bootstrap_theme_helper/tests/Kernel/BclComponentsOverrideTest.php
> +    file_put_contents("$path/bcl-card/bcl-card.html.twig", 'Card: oe_bootstrap_theme version');
OK, discussed in the chat. @brummbar is correct that this could break other tests, as they run on the same codebase. Will find a solution to keep the codebase unchanged.

2021-10-29 06:43 UTC, claudiu-cristea commented on modules/oe_bootstrap_theme_helper/tests/Kernel/BclComponentsOverrideTest.php
> +        '#type' => 'pattern',
I've fixed this by creating BCL components & patterns only for the purpose of testing.

2021-10-29 06:47 UTC, closed without merging