OEL-579: Medley branch with all upgrade to BCL 0.9.0
openeuropa/oe_bootstrap_theme pull request #97
Opened 2021-10-14 15:17 UTC by escuriola

Jira issue(s):
- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-579

Contains: 
- OEL-474: All pattern tests with BCL 0.9.0 (https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-474)
- OEL-424/FRONT-2488: select multiple with slimSelect (https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-424)
- OEL-583/FRONT-2491: Toast (https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-583)

2021-10-21 11:08 UTC, drishu requested changes

2021-10-21 11:08 UTC, drishu commented on templates/patterns/navbar/pattern-navbar.html.twig
> +      class='navbar-toggler'
what's the change to single quotes for ?

2021-10-21 11:08 UTC, drishu commented on templates/patterns/toasts/pattern-toasts.html.twig
> +{#
pls also implement the feedback I left in the toast PR

2021-10-21 12:37 UTC, drishu requested changes

2021-10-21 12:37 UTC, drishu commented on tests/fixtures/markup_rendering.yml
> +submit:
lets do more variants for all these, example here in submit we can:
check for btn-primary, btn-secondary, and a disabled one

2021-10-25 08:57 UTC, escuriola commented on tests/fixtures/markup_rendering.yml
> +submit:
This part is done. I did tests for each pattern with all variants.

2021-10-27 13:49 UTC, drishu commented on templates/patterns/toasts/pattern-toasts.html.twig
> +{#
we postpone till FRONT issue is resolved

2021-10-27 16:04 UTC, drishu approved these changes

2021-10-28 07:45 UTC, abel-santos-corral approved these changes

2021-10-28 07:46 UTC, merged